name: CI Groupe7

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_Groupe7:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Installer les dépendances
        run: npm ci

      - name: Construire le projet
        run: npm run build

      - name: Publier le dossier dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  test_Groupe7:
    needs: build_Groupe7
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22, 24]

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Installer les dépendances
        run: npm ci

      - name: Lancer les tests
        run: npm test

  deploy_Groupe7:
    needs: test_Groupe7
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Déploiement
        run: echo "Déploiement effectué sur la branche main."